version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
